import time
import torch
import torch.nn as nn


class EncoderDecoderSoftRobot(nn.Module):

  def __init__(
      self,
      hist_input_dim=13,  # Past dimensions (e.g. V7: 9 kinematics + 4 tension)
      future_action_dim=4,  # Candidate future actions (e.g. 4 delta_meta_m)
      hidden_dim=128,
      num_layers=2,
      output_dim=3,
      dropout=0.1,
  ):
    super(EncoderDecoderSoftRobot, self).__init__()

    self.hidden_dim = hidden_dim
    self.num_layers = num_layers

    # 1. ENCODER: Processes the 20 history steps
    self.encoder = nn.LSTM(
        hist_input_dim, hidden_dim, num_layers, batch_first=True, dropout=dropout
    )

    # 2. DECODER: Receives the projected future actions (10 steps) + encoder hidden state
    self.decoder = nn.LSTM(
        future_action_dim,
        hidden_dim,
        num_layers,
        batch_first=True,
        dropout=dropout,
    )

    # 3. OUTPUT HEAD: Projects the memory to 3D (x, y, z) coordinates
    self.fc_out = nn.Sequential(
        nn.Linear(hidden_dim, 64),
        nn.ReLU(),
        nn.Linear(64, output_dim),  # 3D: rel_x, rel_y, rel_z
    )

  def encode_history(self, x_hist):
    """Processes the past history of 20 steps.

    x_hist shape: (Batch_Size, 20, hist_input_dim)
    """
    _, (h_n, c_n) = self.encoder(x_hist)
    return h_n, c_n

  def decode_future(self, x_future_actions, h_state, c_state):
    """Predicts the 10 future steps based on the candidate actions.

    x_future_actions shape: (N_candidates, 10, future_action_dim)
    """
    out_dec, _ = self.decoder(x_future_actions, (h_state, c_state))
    # out_dec shape: (N_candidates, 10, hidden_dim)
    predictions = self.fc_out(out_dec)
    # predictions shape: (N_candidates, 10, 3)
    return predictions

  def forward(self, x_hist, x_future_actions):
    """Standard batch-by-batch training."""
    h_n, c_n = self.encode_history(x_hist)
    return self.decode_future(x_future_actions, h_n, c_n)

  def predict_candidates(self, x_hist_single, x_candidates):
    """Ultra-fast inference for real-time MPC.

    - x_hist_single: (1, 20, hist_input_dim) -> Current history of the plant.
    - x_candidates:  (N_cand, 10, future_action_dim) -> N control sequences to evaluate.
    """
    N_cand = x_candidates.size(0)

    # 1. Encode the past ONLY ONCE
    h_single, c_single = self.encode_history(x_hist_single)

    # 2. Replicate the latent state for the N candidates on GPU (Memory Expand)
    # Resulting shape: (num_layers, N_cand, hidden_dim)
    h_expanded = h_single.expand(-1, N_cand, -1).contiguous()
    c_expanded = c_single.expand(-1, N_cand, -1).contiguous()

    # 3. Decode all trajectories in parallel
    return self.decode_future(x_candidates, h_expanded, c_expanded)


# =====================================================================
# DEMONSTRATION AND PERFORMANCE TEST (PARALLEL BENCHMARK)
# =====================================================================
if __name__ == '__main__':
  device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
  print(f'⚡ Evaluando Predictor MPC en: {device}')

  # Test hyperparameters
  T_IN = 20  # Past history
  T_OUT = 10  # Prediction horizon
  N_CANDIDATES = 2000  # 2,000 candidate sequences in parallel!

  model = EncoderDecoderSoftRobot(
      hist_input_dim=13, future_action_dim=4, hidden_dim=128, num_layers=2
  ).to(device)

  model.eval()

  # Input simulation
  # 1 real robot history (1 batch, 20 steps, 13 variables)
  dummy_hist = torch.randn(1, T_IN, 13, device=device)

  # 2,000 future control candidates generated by an MPC (2000 batch, 10 steps, 4 motors)
  dummy_candidates = torch.randn(N_CANDIDATES, T_OUT, 4, device=device)

  # GPU warmup
  with torch.no_grad():
    _ = model.predict_candidates(dummy_hist, dummy_candidates)

  # Inference time measurement
  start_time = time.time()
  with torch.no_grad():
    # Output matrix: (2000 candidates, 10 future steps, 3D positions)
    predicciones_3d = model.predict_candidates(dummy_hist, dummy_candidates)

  if device.type == 'cuda':
    torch.cuda.synchronize()

  elapsed_ms = (time.time() - start_time) * 1000.0

  print('\n✅ Test completado con éxito:')
  print(f' ▫ Shape de salida: {predicciones_3d.shape} (N_candidatos, T_out, 3D)')
  print(
      f' ▫ Tiempo de evaluación para {N_CANDIDATES} candidatos:'
      f' {elapsed_ms:.2f} ms'
  )